name: deploy

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  deployment:
    environment: ${{ inputs.targetEnv }}
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - run: echo "demonstrates using an env variable to determine the runner type"
      - run: echo "were using an ubuntu flavor since this is personal repo, but we could also use a codebuild runner, for example:"
      - run: echo "codebuild-${{ vars.CODE_BUILD_PROJECT_NAME  }}-${{ github.run_id }}-${{ github.run_attempt }}"

      - name: CDK Deploy
        run: echo "pretending to cdk deploy..."

  smoke-test:
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    needs: deployment
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Smoke Test
        run: echo "pretending to run smoke tests..."

