name: deploy
# make it easy to tell which deployment is running
run-name: deploy ${{ inputs.commit_to_deploy || 'main' }} to ${{ inputs.target_env || 'dev' }}

concurrency:
  # only allow one deployment at a time per environment
  group: deploy-${{ github.event.inputs.target_env || 'dev' }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment to deploy to"
        type: environment
        required: true

      commit_to_deploy:
        description: "Commit to deploy. This can be a branch, tag, or SHA"
        type: string
        required: true
  push:
    branches:
      - main

jobs:
  setup:
    # default to dev when triggered by push
    environment: ${{ inputs.target_env || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Runner Type
        run: echo "determining runner type based on environment"

    outputs:
      runner: ubuntu-${{ vars.UBUNTU_VERSION }}
      code_build_runner: "codebuild-${{ vars.CODE_BUILD_PROJECT_NAME  }}-${{ github.run_id }}-${{ github.run_attempt }}"

  deployment:
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
        with:
          # default to main when triggered by push
          ref: ${{ inputs.commit_to_deploy || 'main' }}
          fetch-depth: 0 # fetch all history for all branches and tags
          fetch-tags: true

      - run: echo "demo using environment variables to determine the runner type"
      - run: echo "using ubuntu flavor since this repo can't access aws,"
      - run: echo "but we could also use a codebuild runner. e.g."
      - run: echo "${{ needs.setup.outputs.code_build_runner }}"

      - name: Verify Version
        run: git describe --tags

      - name: Verify Most Recent Commit
        run: git show

      - name: CDK Deploy
        run: echo "pretending to cdk deploy..."

  smoke-test:
    needs: [setup, deployment]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Smoke Test
        run: echo "pretending to run smoke tests..."


