name: deploy
# make it easy to tell which deployment is running
run-name: deploy ${{ github.ref_name }} to ${{ inputs.target_env || 'dev' }}

concurrency:
  # only allow one deployment at a time per environment
  group: deploy-${{ inputs.target_env || 'dev' }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment to deploy to"
        type: environment
        required: true
        default: dev
      skip_pause:
        description: "Skip pause for testing (only applies to deploying feature branches to dev)"
        type: boolean
        required: true
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      # default to dev when triggered by push
      target_env: ${{ inputs.target_env || 'dev' }}

    steps:
      - name: Determine Runner Type
        run: echo "UBUNTU_VERSION_VAR_NAME=UBUNTU_VERSION_$(echo $target_env)" >> $GITHUB_ENV

      - run: echo dolla $UBUNTU_VERSION_VAR_NAME
      - run: echo env ${{ env.UBUNTU_VERSION_VAR_NAME }}

      - name: Verify UBUNTU_VERSION_{ENV} is set for ${{ env.target_env }}
        if: ${{ vars[env.UBUNTU_VERSION_VAR_NAME] == '' }}
        run: |
          echo "$UBUNTU_VERSION_VAR_NAME is not configured"
          exit 1

    outputs:
      target_env: ${{ env.target_env }}
      runner: ubuntu-${{ vars[env.UBUNTU_VERSION_VAR_NAME] }}

  deployment:
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner }}
    environment: ${{ needs.setup.outputs.target_env }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
          fetch-tags: true

      - run: echo "demo using environment variables to determine the runner type"
      - run: echo "running on ${{ needs.setup.outputs.runner }}"
      - run: cat /etc/lsb-release

      - name: Verify Version
        run: git describe --tags

      - name: Verify Most Recent Commit
        run: git show

      - name: CDK Deploy
        run: echo "pretending to cdk deploy..."

  smoke-test:
    needs: [setup, deployment]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v4

      - name: Smoke Test
        run: echo "pretending to run smoke tests..."

  # This runs only when deploying a feature branch to dev.
  # It's marked as a deployment to the "dev-testing" environment which is not a
  # real environment but a mechanism to block additional deployments to dev until
  # this job is complete. This allows the developer to test the deployment in dev
  # before merging the PR to main.
  pause-for-dev-testing:
    if: ${{ !inputs.skip_pause
      && inputs.target_env == 'dev'
      && github.ref_name != 'main'
      }}
    runs-on: ubuntu-latest
    environment: dev-testing
    needs: [setup, deployment, smoke-test]
    steps:
      - run: echo "done testing"
